// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back.Data.Models;

public partial class Asiento
{
    public int IdAsiento { get; set; }

    public int? Numero { get; set; }

    public int? Fila { get; set; }

    public int? IdSala { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}