// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back.Data.Models;

public partial class Promocione
{
    public int CodPromocion { get; set; }

    public TimeOnly? HoraDesde { get; set; }

    public TimeOnly? HoraHasta { get; set; }

    public int? Dia { get; set; }

    public int? DescPorcentaje { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}