// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back.Data.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public int? NroSala { get; set; }

    public int? Capacidad { get; set; }

    public virtual ICollection<Asiento> Asientos { get; set; } = new List<Asiento>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}