// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back.Data.Models;

public partial class Ticket
{
    public int IdTicket { get; set; }

    public int? CodFuncion { get; set; }

    public int? IdAsiento { get; set; }

    public int? CodTransaccion { get; set; }

    public virtual Funcione CodFuncionNavigation { get; set; }

    public virtual Transaccione CodTransaccionNavigation { get; set; }

    public virtual Asiento IdAsientoNavigation { get; set; }
}